project:
  type: website

website:
  title: "Ryan Light"
  navbar:
    background: "light"
    left:
      #- href: index.qmd
       # text: home 
      - text: "Publications" 
        file: publications.qmd
      - text: "Teaching" 
        file: teaching.qmd
      - text: "About"
        file: about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

